packages:
  - "bot"
  - "bots/*"
  - "utility/*"
  - "packages/*"

catalog:
  "@eslint/js": "^9.23.0"
  "@typescript-eslint/eslint-plugin": "^8.25.0"
  "@typescript-eslint/parser": "^8.25.0"
  "eslint": "^9.23.0"
  "globals": "^15.14.0"
  "typescript-eslint": "^8.19.1"

  "date-fns": "^2.30.0"
  "random-js": "^2.1.0"
  "discord.js": "^14.18.0"
  "telegraf": "^4.16.3"
  "openai": "4.83.0"

  "@types/node": "^20.16.1"
  "dotenv": "^16.4.7"
  "nodemon": "^3.1.7"
  "ts-node": "^10.9.2"
  "tsc-alias": "^1.8.10"
  "tsconfig-paths": "^4.2.0"
  "typescript": "^5.7.3"

  "@thevoidcommunity/the-void-database": "4.0.1-beta.1"
  "f-formatter": "0.3.1"
  "fock-logger": "4.0.1a"