packages:
  - "bot"
  - "bots/*"
  - "utility/*"
  - "packages/*"

catalog:
  "@eslint/js": "^9.18.0"
  "eslint": "^9.18.0"
  "typescript-eslint": "^8.19.1"

  "globals": "^15.14.0"
  "date-fns": "^2.30.0"
  "random-js": "^2.1.0"
  "discord.js": "^14.18.0"
  "telegraf": "^4.16.3"
  "openai": "4.83.0"

  "@types/node": "^20.16.1"
  "dotenv": "^16.4.7"
  "nodemon": "^3.1.7"
  "ts-node": "^10.9.2"
  "tsc-alias": "^1.8.10"
  "tsconfig-paths": "^4.2.0"
  "typescript": "^5.7.3"

  "@thevoidcommunity/the-void-database": latest
  "f-formatter": "latest"
  "fock-logger": "latest"