name: Code Scanner

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  format:
    name: Scanner
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: pnpm-setup
        uses: pnpm/action-setup@v2
        with:
            version: 10.4.1

      - name: Install ESLint
        run: pnpm install

      - name: Run ESLint
        run: pnpm run lint
        continue-on-error: false